name = "proxilion"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

[build]
command = "npm run build"

[env.production]
name = "proxilion-production"
workers_dev = false

[env.staging]
name = "proxilion-staging"
workers_dev = true

