#!/usr/bin/env bash
# Proxilion reference demo — entrypoint.
#
# Brings up the dev compose stack and runs all four scenarios in sequence,
# printing what's happening at each step.
#
# Authority: spec.md §4.4. The headline scenario is `02-confused-deputy.sh`
# — it demonstrates PIC monotonicity refusing a "can Alice's agent read
# Bob's data?" attempt. This is the unique value of the project.

set -euo pipefail

cd "$(dirname "$0")/.."

banner() {
  printf '\n\033[1;36m'
  printf '%.0s═' {1..72}; echo
  printf '  %s\n' "$*"
  printf '%.0s═' {1..72}; echo
  printf '\033[0m'
}

step() { printf '\n\033[1;34m▶ %s\033[0m\n' "$*"; }

banner "Proxilion reference demo"
echo "What you'll see:"
echo "  1. PIC chain inspection — root principal carried unchanged across hops"
echo "  2. Confused-deputy attack rejected by the Trust Plane's monotonicity invariant"
echo "  3. Blocked Layer-B action → operator override → attested PCA branch"
echo "  4. Killswitch revokes the session; subsequent requests fail"
echo
echo "Stack: proxy + Trust Plane + Postgres + NATS + mock-Okta (all in docker compose)"

step "Generating .env if missing"
if [ ! -f .env ]; then
  KEY=$(openssl rand -hex 32)
  TKEY=$(openssl rand -hex 32)
  cat > .env <<EOF
# Generated by demo/run.sh — regenerate with `rm .env && ./demo/run.sh`
TRUST_PLANE_CAT_KEY_HEX=$KEY
PROXILION_TOKEN_ENCRYPTION_KEY=$TKEY
PROXILION_DEMO=1
PROXILION_CUSTOMER_DOMAIN=acme.com
PROXILION_POLICY_PATH=/config/policy.yaml
# Set these to drive the real OAuth flow against Google; absent → adapters
# fall back to bearer-rejection at the middleware (sufficient for the demo).
GOOGLE_CLIENT_ID=demo-google-client
GOOGLE_CLIENT_SECRET=demo-google-secret
EOF
  echo "  wrote .env"
fi

step "docker compose up -d --wait"
docker compose up -d --wait postgres trust-plane mock-okta nats
docker compose up -d --wait proxy || true
sleep 3

step "Health"
curl -sk https://127.0.0.1:8443/healthz | jq -r '"  ready=\(.ready)  checks:\(.checks | to_entries | map("\(.key)=\(.value.ok)") | join(" "))"'

banner "Scenario 1 — PIC chain walk (the happy path)"
./demo/scripts/01-pic-chain-walk.sh

banner "Scenario 2 — Confused-deputy attack (the headline)"
./demo/scripts/02-confused-deputy.sh

banner "Scenario 3 — Blocked action + operator override"
./demo/scripts/03-blocked-override.sh

banner "Scenario 4 — Killswitch"
./demo/scripts/04-killswitch.sh

banner "Done. Next steps:"
echo "  • Inspect action stream: docker run --rm --network proxilion-dev_default natsio/nats-box:latest \\"
echo "      nats -s nats://nats:4222 sub 'actions.>'"
echo "  • CLI: cargo run -p proxilion-cli -- actions tail --endpoint https://127.0.0.1:8443 --insecure"
echo "  • Tear down: docker compose down -v"
